name: laser-interferometry
channels:
  - conda-forge
  - defaults
dependencies:
  - python>3.6
  - pytest
  - watermark
  - jupyterlab
  - ipywidgets >= 6.0.0
  - cookiecutter
  - pandas
  - matplotlib
  - numpy
  - scipy
  - sphinx
  - pip:
    - ffmpeg
    - nbsphinx
    - nbval
    - nbdime
    - recipy
    - hypothesis
    - pipenv
    - datapackage
    - jupyter-repo2docker
